### ISSUE TITLE
Make payload structs' fields pub

### ISSUE THREAD

**Issue by leodutra** [biomunky/newsapi#22]
Hi guys,
I'm migrating my chatbot from JS :+1:  to Rust :rocket: and thank you for creating this crate. :smile: 

I'm trying to use the payload objects, but Rust 1.39 expects them to be `pub`. I tried to implement From, but whenever I try to access the struct fields, the RLS and compiler won't let me.

I don't know if there's any other sane way as this is my first big Rust project, so please let me know... maybe other newbies will find the same issue.

**Comment by biomunky** [comment]
Hello, sorry for the delayed reply, I haven't really been looking to hard at this. I've opened a [PR](https://github.com/biomunky/newsapi/pull/23) that, I think, should do what you need - make the fields accessible outside the newapi code. Somehow managed to completely overlook this!

**Comment by biomunky** [comment]
@leodutra if you update to version 0.3.0 the problems should be sorted. If you have any other issues please feel free to raise a PR, we were/are using this library as a way to learn Rust.

**Comment by leodutra** [comment]
That's great. I'm actually using your lib with the same purpose, migrating my personal chatbot to Rust to learn.
Are you accepting PRs?

**Comment by biomunky** [comment]
Absolutely.

**Comment by leodutra** [comment]
Feels great as is right now, but if I find any possible improvement, I'll bring to your appreciation and produce some PR, 
Thanks.
